#ifndef COMPONENTFULL_SEARCH_GLOBAL_H
#define COMPONENTFULL_SEARCH_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMPONENTFULL_SEARCH_LIBRARY)
#  define COMPONENTFULL_SEARCHSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COMPONENTFULL_SEARCHSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COMPONENTFULL_SEARCH_GLOBAL_H
