#!/bin/bash

LD_LIBRARY_PATH=$PWD/build/Common/ComponentsCore5alpha/:${LD_LIBRARY_PATH}
LD_LIBRARY_PATH=$PWD/build/Common/ComponentSystemGuiCoreNg/:${LD_LIBRARY_PATH}
LD_LIBRARY_PATH=$PWD/build/Common/ComponentProcessingGui/:${LD_LIBRARY_PATH}
LD_LIBRARY_PATH=$PWD/build/Common/ComponentFull_Search/src/:${LD_LIBRARY_PATH}
LD_LIBRARY_PATH=$PWD/build/Common/Matrix/src/:${LD_LIBRARY_PATH}
LD_LIBRARY_PATH=$PWD/build/Common/TCP/src/:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH

# check choosen component to build
if [ "$1" = "--Gui" ]; then
    ./build/GuiApplication/test/GuiApplicationTest
elif [ "$1" = "--Service" ]; then
    ./build/ServiceApplication/test/ServiceApplicationTest
elif [ "$1" = "--Common" ]; then
    ./build/Common/Matrix/test/MatrixTest
    ./build/Common/TCP/test/TCPTest
    ./build/Common/ComponentFull_Search/test/Full_SearchTest
elif [ "$1" = "--Matrix" ]; then
    ./build/Common/Matrix/test/MatrixTest
elif [ "$1" = "--TCP" ]; then
    ./build/Common/TCP/test/TCPTest
elif [ "$1" = "--Full_Search" ]; then
    ./build/Common/ComponentFull_Search/test/Full_SearchTest
else
    # default - run all tests
    ./build/GuiApplication/test/GuiApplicationTest
    ./build/ServiceApplication/test/ServiceApplicationTest
    ./build/Common/Matrix/test/MatrixTest
    ./build/Common/TCP/test/TCPTest
    ./build/Common/ComponentFull_Search/test/Full_SearchTest
fi


