#ifndef COMPONENTSCORE_GLOBAL_H
#define COMPONENTSCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMPONENTSCORE5A_LIBRARY)
#  define COMPONENTSCORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define COMPONENTSCORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COMPONENTSCORE_GLOBAL_H
