#ifndef COMPONENTROCESSINGGUI_GLOBAL_H
#define COMPONENTROCESSINGGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMPONENTPROCESSINGGUI_LIBRARY)
#  define COMPONENTPROCESSINGGUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define COMPONENTPROCESSINGGUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COMPONENTPROCESSINGGUI_GLOBAL_H
