#ifndef COMPONENTSYSTEMGUICORENG_GLOBAL_H
#define COMPONENTSYSTEMGUICORENG_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMPONENTSYSTEMGUICORENG_LIBRARY)
#  define COMPONENTSYSTEMGUICORENGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COMPONENTSYSTEMGUICORENGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COMPONENTSYSTEMGUICORENG_GLOBAL_H
